version: '3'

services:
  mobsf:
    image: opensecurity/mobile-security-framework-mobsf:latest
    container_name: mobsf
    ports:
      - "8000:8000"
    restart: always
    # Optional: If MobSF needs to communicate with external devices or Genymotion, add environment variables and exposed ports as needed
    # environment:
    #   - MOBSF_ANALYZER_IDENTIFIER=<adb device identifier>

  django:
    build: .
    container_name: droidkey_backend
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - mobsf
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=127.0.0.1 localhost
